//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuentas()
        {
            this.CuentaPartida = new HashSet<CuentaPartida>();
        }
    
        public int ID_Cuenta { get; set; }
        public string Grupo { get; set; }
        public string Subgrupo { get; set; }
        public string Cuenta { get; set; }
        public string Subcuenta { get; set; }
        public string CuentaDetalle { get; set; }
        public string NombreCuenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaPartida> CuentaPartida { get; set; }
    }
}
