//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public int ID_Empresa { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public string NombreComercial { get; set; }
        public string NombreAbreviado { get; set; }
        public string RepresentanteLegal { get; set; }
        public string ActividadEmpresa { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string NIT { get; set; }
        public string Registro { get; set; }
        public Nullable<decimal> CapAutorizado { get; set; }
        public Nullable<decimal> CapSuscrito { get; set; }
        public Nullable<decimal> CapPagado { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
