//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partidas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partidas()
        {
            this.CuentaPartida = new HashSet<CuentaPartida>();
        }
    
        public int ID_Partida { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cheque { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaPartida> CuentaPartida { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
